- name : Set Hostname
  ansible.builtin.shell: set-hostname {{env}}-{{component}}

- name: Disable NodeJs default version
  ansible.builtin.shell: dnf module disable nodejs -y
- name: Enable NodeJs 18 version
  ansible.builtin.shell: dnf module enable nodejs:18 -y
- name: Install NodeJs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Copy catalogue Services file
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Add Application user
  ansible.builtin.user:
    name: expense

- name: Import Common Role- App Pre-requisites
  ansible.builtin.import_role:
     name: common
     tasks_from: app-prereq
  vars:
    app_dir: /app
    component: catalogue
    app_user: roboshop


- name: Download NodeJs Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app
- name: Install New Relic NodeJS Library
  ansible.builtin.shell: npm install newrelic --save
  args:
    chdir: /app

- name: Copy Backend StartUP Script
  ansible.builtin.template:
    src: run.sh
    dest: /app/run.sh

- name: Install MYSQL Client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Load Schema
  ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', '{{env}}.rds.endpoint', region='us-east-1' ) }} -u{{ lookup('amazon.aws.aws_ssm', '{{env}}.rds.username', region='us-east-1' ) }} -p{{ lookup('amazon.aws.aws_ssm', '{{env}}.rds.password', region='us-east-1' ) }} < /app/schema/backend.sql


- name: Import ELK Role- Filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Start backend service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Import Prometheus- Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter

