- name: Copy MongoDB repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongo Repo file
  ansible.builtin.dnf:
    name: mongodb-org-shell
    state: installed
