route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: email
    email_configs:
      - to: minhajfathima1023@gmail.com      # you@example.com
        from: minhajfathima1023@gmail.com  # alertmanager@example.com
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
        auth_username: "{{ lookup('aws_ssm', 'ses.username', region='us-east-1' ) }}"
        auth_password: "{{ lookup('aws_ssm', 'ses.password', region='us-east-1' ) }}"
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
